# Generated by Django 3.1.12 on 2025-04-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20250424_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='taskID',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deleteTask',
        ),
    ]
