# Generated by Django 3.1.12 on 2025-04-24 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20250424_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytics',
            name='date',
        ),
    ]
