# Generated by Django 3.1.12 on 2025-04-24 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_analytics_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('weight', models.DecimalField(decimal_places=1, help_text='Weight in kilograms', max_digits=5)),
                ('sleep_hours', models.DecimalField(decimal_places=1, help_text='Sleep hours', max_digits=4)),
                ('thoughts', models.TextField(help_text="User's thoughts on the day or any additional comments")),
                ('mood', models.CharField(choices=[('very_bad', 'Very Bad'), ('bad', 'Bad'), ('neutral', 'Neutral'), ('good', 'Good'), ('very_good', 'Very Good')], help_text='Mood rating', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
