# Generated by Django 3.1.12 on 2025-04-24 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20250424_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coachfeedback',
            old_name='feedback',
            new_name='feedback_text',
        ),
    ]
