# Generated by Django 3.1.12 on 2025-04-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20250424_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachfeedback',
            name='date_responded',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coachfeedback',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
