# Generated by Django 3.1.12 on 2025-04-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20250424_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachfeedback',
            name='date_user_responded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coachfeedback',
            name='user_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
